[params.busuanzi]
    enable = true
    site_uv = true
    site_ur_pre = '<i class="fa fa-user"></i>'
    site_pv = true
    site_pv_pre = '<i class="fa fa-eye"></i>'
    page_pv = true
    page_pv_pre = '<i class="fa fa-eye fa-fw"></i>'
